#!/usr/bin/env python3
"""Generate every Miyar DocType JSON from ERPNext-DocTypes.md (sections 3–16)."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_lib import (  # noqa: E402
	ADMIN,
	C_E,
	C_P,
	K_E,
	K_P,
	L_E,
	L_P,
	CONSULTANTS,
	CONTRACTORS,
	LABS,
	PARTIES,
	SM,
	SPT,
	SUP,
	VISITOR,
	admin_full,
	child,
	col,
	dt,
	f,
	full,
	master_perms,
	readp,
	rwc,
	sec,
	tab,
	write_doctype,
	P,
)

APP_ROOT = Path(__file__).resolve().parents[1]

# Closed STS / operational selects (section 5)
REQ_STS = "STS09\nSTS10\nSTS11\nSTS12\nSTS13\nSTS14\nSTS15\nSTS16\nSTS26"
TL_STS = "STS17\nSTS18\nSTS19\nSTS20\nSTS21"
CAT_STS = "STS01\nSTS02\nSTS03"
DIR_STS = "STS04\nSTS05"
RTG_STS = "STS06\nSTS07\nSTS08"
DEL_STS = "STS22\nSTS23\nSTS24\nSTS25"
QUOTE_STS = "Pending\nQuoted\nAccepted\nRejected\nExpired"
REG_STS = "Draft\nSubmitted\nUnder Review\nActivated\nRejected"
INV_STS = "Draft\nDue\nOverdue\nPaid"
KN_STS = "مسودة\nساري\nمؤرشف"
TPL_STS = "ساري\nمسودة\nمؤرشف"
POL_STS = "ساري\nمسودة\nمنتهٍ"
BH_STS = "Ready\nIn Progress\nDone"
FS_STS = "Ready\nIn Progress\nDone"
TR_STS = "Draft\nPending OTP\nDone\nRejected\nClarification"
ENG_STS = "COMPLIANT\nNON_COMPLIANT\nPARTIALLY_COMPLIANT\nNOT_EVALUABLE\nNOT_APPLICABLE"
INT_STS = "يعمل\nتأخر\nصيانة"
TKT_STS = "مفتوحة\nقيد المعالجة\nبانتظار الإدارة\nمغلقة"
COMPL = "\nok\nfail"


def children():
	return [
		child(
			"Rating Dimension",
			[
				f("dimension_key", "Data", "المفتاح", reqd=1),
				f("label_ar", "Data", "التسمية", reqd=1),
				f("weight", "Float", "الوزن"),
			],
		),
		child(
			"SAAC Accreditation",
			[
				f("saac_number", "Data", "رقم SAAC"),
				f("scope", "Small Text", "النطاق"),
				f("expires_on", "Date", "ينتهي في"),
				f("certificate", "Attach", "الشهادة"),
			],
		),
		child(
			"Organization Specialty",
			[f("specialty", "Link", "التخصص", opt="Organization Specialty Def", reqd=1)],
		),
		child("Reference Test UOM", [f("uom", "Link", "وحدة القياس", opt="UOM", reqd=1)]),
		child("Reference Test Method", [f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1)]),
		child(
			"Reference Test Result Field",
			[
				f("field_key", "Data", "المفتاح", reqd=1),
				f("label_ar", "Data", "التسمية", reqd=1),
				f("uom", "Data", "الوحدة"),
				f("sort_order", "Int", "الترتيب"),
			],
		),
		child(
			"Method Step",
			[
				f("step", "Int", "الخطوة"),
				f("instruction", "Text", "التعليمات"),
			],
		),
		child(
			"Method Specimen Field",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("uom", "Data", "الوحدة"),
			],
		),
		child(
			"Method Equipment Type",
			[f("equipment_type", "Link", "نوع المعدة", opt="Equipment Type", reqd=1)],
		),
		child("Catalog Method", [f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1)]),
		child("Quote Service", [f("service_type", "Link", "نوع الخدمة", opt="Service Type", reqd=1)]),
		child(
			"Miyar Quote Item",
			[
				f("reference_test", "Link", "الاختبار", opt="Reference Test", reqd=1),
				f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1),
				f("uom", "Link", "الوحدة", opt="UOM"),
				f("base_price", "Currency", "السعر الأساسي", ro=1, opt="SAR"),
				f("price", "Currency", "سعر العرض", reqd=1, opt="SAR"),
				f("sla_days", "Int", "مدة التنفيذ (يوم)"),
			],
		),
		child("Contract Service", [f("service_type", "Link", "نوع الخدمة", opt="Service Type", reqd=1)]),
		child(
			"Contract Item",
			[
				f("reference_test", "Link", "الاختبار", opt="Reference Test"),
				f("test_method", "Link", "الطريقة", opt="Test Method"),
				f("uom", "Link", "الوحدة", opt="UOM"),
				f("price", "Currency", "السعر المثبت", opt="SAR"),
				f("sla_days", "Int", "SLA (يوم)"),
			],
		),
		child(
			"Request Rules Snapshot",
			[
				f("lab_decision_hours", "Int", "مهلة المختبر (ساعة)"),
				f("consultant_decision_hours", "Int", "مهلة الاستشاري (ساعة)"),
				f("vat_rate", "Percent", "نسبة الضريبة"),
				f("min_lead_hours", "Int", "أول موعد ≥ ساعات"),
				f("geofence_meters", "Float", "نطاق التحقق (م)"),
				f("max_tests_per_request", "Int", "أقصى اختبارات"),
				f("proposed_slots", "Int", "عدد المواعيد"),
			],
		),
		child(
			"Request Time Slot",
			[
				f("slot_date", "Date", "التاريخ", reqd=1),
				f("from_time", "Time", "من", reqd=1),
				f("to_time", "Time", "إلى", reqd=1),
			],
		),
		child(
			"Request Attachment",
			[
				f("file", "Attach", "الملف"),
				f("file_name", "Data", "اسم الملف"),
				f("file_size", "Data", "الحجم"),
			],
		),
		child(
			"Request History",
			[
				f("at", "Datetime", "الوقت"),
				f("actor", "Data", "الفاعل"),
				f("actor_role", "Data", "الدور"),
				f("action", "Small Text", "الإجراء"),
				f("detail", "Small Text", "التفصيل"),
			],
		),
		child(
			"Test Result Value",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("uom", "Data", "الوحدة"),
				f("value", "Data", "القيمة"),
				f("limit_text", "Small Text", "حد القبول"),
				f("compliance", "Select", "المطابقة", opt=COMPL),
			],
		),
		child(
			"Test Specimen Value",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("uom", "Data", "الوحدة"),
				f("value", "Data", "القيمة"),
			],
		),
		child("Test Equipment Use", [f("asset", "Link", "المعدة", opt="Asset", reqd=1)]),
		child("Test Photo Link", [f("photo", "Link", "الدليل", opt="Photo Evidence")]),
		child(
			"Study Site Condition",
			[f("site_condition", "Link", "ظرف الموقع", opt="Site Condition", reqd=1)],
		),
		child(
			"Study Polygon Point",
			[
				f("seq", "Int", "الترتيب"),
				f("northing", "Float", "شمال", reqd=1),
				f("easting", "Float", "شرق", reqd=1),
			],
		),
		child("Engine Basis Line", [f("line", "Small Text", "الأساس")]),
		child(
			"Chemical Result",
			[
				f("chemical_test", "Link", "الاختبار", opt="Chemical Test Def"),
				f("label_ar", "Data", "التسمية"),
				f("method_code", "Data", "الطريقة"),
				f("limit_text", "Data", "الحد"),
				f("uom", "Data", "الوحدة"),
				f("value", "Data", "القيمة"),
				f("attachment", "Attach", "مرفق"),
				f("compliance", "Select", "المطابقة", opt=COMPL),
			],
		),
		child(
			"Analysis Computed",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("formula", "Small Text", "الصيغة"),
				f("unit", "Data", "الوحدة"),
				f("inputs", "JSON", "المدخلات"),
				f("value", "Data", "القيمة", ro=1),
			],
		),
		child(
			"Analysis Key Value",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("value", "Small Text", "القيمة"),
				f("source", "Select", "المصدر", opt="engine\nknowledge\nmanual"),
			],
		),
		child("Analysis Attachment", [f("file", "Attach", "الملف")]),
		child(
			"Sample Test Row",
			[
				f("test_label", "Data", "الاختبار"),
				f("test_method", "Link", "الطريقة", opt="Test Method"),
				f("mandatory", "Check", "إلزامي"),
				f("value", "Data", "القيمة"),
				f("uom", "Data", "الوحدة"),
				f("attachment", "Attach", "مرفق"),
				f("limit_text", "Data", "الحد"),
				f("compliance", "Select", "المطابقة", opt=COMPL),
			],
		),
		child(
			"Rating Score",
			[
				f("dimension_key", "Data", "البعد"),
				f("label_ar", "Data", "التسمية"),
				f("score", "Int", "الدرجة"),
			],
		),
		child(
			"Sample Dimension",
			[
				f("dim_key", "Data", "المفتاح"),
				f("dim_value", "Data", "القيمة"),
			],
		),
		child(
			"Custody Event",
			[
				f("at", "Datetime", "الوقت"),
				f("step", "Link", "الخطوة", opt="Custody Step", reqd=1),
				f("by", "Data", "بواسطة"),
				f("location", "Data", "المكان"),
				f("note", "Small Text", "ملاحظة"),
				f("temp_c", "Float", "الحرارة °م"),
			],
		),
		child("Archived Sample Photo", [f("photo", "Link", "الصورة", opt="Photo Evidence")]),
		child("Borehole Photo Link", [f("photo", "Link", "الصورة", opt="Photo Evidence")]),
		child(
			"Invoice Item",
			[
				f("description", "Data", "الوصف"),
				f("reference_test", "Link", "الاختبار", opt="Reference Test"),
				f("qty", "Float", "الكمية"),
				f("rate", "Currency", "السعر", opt="SAR"),
				f("amount", "Currency", "المبلغ", opt="SAR"),
			],
		),
		child(
			"Formula Definition",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("formula", "Small Text", "الصيغة"),
				f("unit", "Data", "الوحدة"),
				f("input_schema", "JSON", "مدخلات"),
			],
		),
		child(
			"Analytical Field Def",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("source", "Data", "المصدر"),
			],
		),
		child(
			"Recommendation Field Def",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("logic_notes", "Small Text", "منطق التوليد"),
			],
		),
		child(
			"Manual Analysis Field Def",
			[
				f("field_key", "Data", "المفتاح"),
				f("label_ar", "Data", "التسمية"),
				f("options", "Small Text", "الخيارات"),
			],
		),
		child("Knowledge Table 21", [f("sbc_row", "Link", "صف Table 2.1", opt="SBC Table 21 Row")]),
		child("Knowledge Trigger", [f("trigger", "Link", "المحفّز", opt="Engine Trigger Rule")]),
		child(
			"Report Template Section",
			[
				f("title", "Data", "العنوان"),
				f("standard_clause", "Data", "البند المعياري"),
				f("sort_order", "Int", "الترتيب"),
				f("field_map", "JSON", "ربط الحقول"),
			],
		),
		child(
			"Template Version History",
			[
				f("version_code", "Data", "الإصدار"),
				f("published_on", "Date", "تاريخ النشر"),
				f("note", "Small Text", "ملاحظة"),
				f("status", "Select", "الحالة", opt=TPL_STS),
			],
		),
	]


def _simple(name, autoname="field:code", extras=None, title="التسمية"):
	fields = []
	if autoname.startswith("field:"):
		fn = autoname.split(":", 1)[1]
		if fn == "code":
			fields.append(f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1, in_std=1))
			fields.append(f("label_ar", "Data", title, reqd=1, in_list=1))
		elif fn == "label_ar":
			fields.append(f("label_ar", "Data", title, reqd=1, unique=1, in_list=1))
			fields.append(f("code", "Data", "الرمز", in_std=1))
		else:
			fields.append(f(fn, "Data", title, reqd=1, unique=1, in_list=1))
			fields.append(f("label_ar", "Data", "التسمية", reqd=1, in_list=1))
	fields.append(f("is_active", "Check", "فعّال", default="1", in_list=1))
	fields.append(f("sort_order", "Int", "الترتيب"))
	if extras:
		fields.extend(extras)
	tf = "label_ar" if any(x["fieldname"] == "label_ar" for x in fields) else None
	return dt(
		name,
		fields,
		autoname=autoname,
		title_field=tf,
		search_fields="code,label_ar",
		permissions=master_perms(),
		quick_entry=1,
		track_changes=1,
	)


def masters():
	return [
		_simple(
			"Organization Type",
			extras=[
				f("can_self_register", "Check", "تسجيل ذاتي"),
				f("appears_in_directory", "Check", "يظهر في الدليل"),
				f("is_operational_party", "Check", "طرف عقد"),
			],
		),
		_simple("Organization Specialty Def", autoname="field:label_ar"),
		_simple("Method Body"),
		dt(
			"Test Method",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1, in_std=1),
				f("method_name", "Data", "اسم الطريقة", reqd=1, in_list=1),
				f("method_body", "Link", "الجسم", opt="Method Body", reqd=1, in_std=1),
				f("is_active", "Check", "فعّال", default="1"),
			],
			autoname="field:code",
			title_field="method_name",
			search_fields="code,method_name",
			permissions=master_perms(),
			track_changes=1,
		),
		_simple("Priority"),
		_simple("Payment Term Code"),
		_simple("Service Type"),
		_simple("Building Type"),
		_simple("Structure Type"),
		_simple("Foundation Type"),
		_simple("Site Condition", autoname="field:label_ar"),
		_simple(
			"USCS Classification",
			extras=[
				f("color_hex", "Data", "لون العرض"),
				f("is_rock", "Check", "صخر"),
			],
		),
		_simple("Sample Type"),
		_simple("Sample Kind"),
		_simple("Borehole Method", autoname="field:label_ar"),
		_simple("Weather Condition", autoname="field:label_ar"),
		_simple("Soil Color", autoname="field:label_ar", extras=[f("allow_other", "Check", "يسمح بوصف حر")]),
		_simple("Gradation", autoname="field:label_ar"),
		_simple("Moisture Description", autoname="field:label_ar"),
		_simple(
			"Spt Density Class",
			extras=[
				f("n_min", "Int", "N من"),
				f("n_max", "Int", "N إلى"),
			],
		),
		_simple("Document Type"),
		_simple("Document Classification", autoname="field:label_ar"),
		_simple("Photo Kind"),
		_simple(
			"Custody Step",
			extras=[f("maps_to_sample_status", "Data", "حالة العينة الناتجة")],
		),
		_simple("Sample Archive Kind", autoname="field:label_ar"),
		_simple("Sample Condition", autoname="field:label_ar"),
		_simple("Equipment Type", autoname="field:label_ar"),
		_simple("Ticket Category", autoname="field:label_ar"),
		_simple("Ticket Status", autoname="field:label_ar"),
		_simple("Payment Channel"),
		_simple("Engine Policy"),
		dt(
			"Engine Profile",
			[
				f("code", "Data", "المفتاح العربي", reqd=1, unique=1, in_list=1),
				f("label_ar", "Data", "التسمية", reqd=1),
				f("is_active", "Check", "فعّال", default="1"),
				f("sort_order", "Int", "الترتيب"),
			],
			autoname="field:code",
			title_field="code",
			permissions=master_perms(),
			track_changes=1,
			description="المفتاح يطابق ENGINE_PROFILES حرفياً ولا يُترجم.",
		),
		_simple(
			"Seismic Site Class",
			extras=[
				f("vs30", "Data", "Vs30"),
				f("n_bar", "Data", "N̄"),
				f("su", "Data", "Su"),
			],
		),
		dt(
			"ECC Control Domain",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("title_ar", "Data", "العنوان", reqd=1, in_list=1),
				f("total_controls", "Int", "إجمالي الضوابط"),
				f("implemented", "Int", "المنفَّذ"),
			],
			autoname="field:code",
			title_field="title_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"SBC Table 21 Row",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("label_ar", "Data", "التسمية", in_list=1),
				f("floors_min", "Int", "أدوار من"),
				f("floors_max", "Int", "أدوار إلى"),
				f("built_area_min_m2", "Float", "مساحة من م²"),
				f("built_area_max_m2", "Float", "مساحة إلى م²"),
				f("base_count", "Int", "العدد الأساسي"),
				f("extra_per_m2", "Float", "جسة إضافية لكل م²"),
				f("count_cap", "Int", "سقف العدد"),
				f("depth_two_thirds_m", "Float", "عمق ثلثين (م)"),
				f("depth_one_third_m", "Float", "عمق ثلث (م)"),
				f("is_special", "Check", "دراسة خاصة"),
				f("knowledge_version", "Link", "إصدار المعرفة", opt="Knowledge Version"),
				f("borehole_count_rule", "Small Text", "قاعدة العدد"),
			],
			autoname="field:code",
			title_field="label_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"Chemical Test Def",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("label_ar", "Data", "التسمية", reqd=1, in_list=1),
				f("test_method", "Link", "الطريقة", opt="Test Method"),
				f("limit_text", "Data", "نص الحد"),
				f("uom", "Data", "الوحدة"),
				f("sort_order", "Int", "الترتيب"),
				f("is_mandatory", "Check", "إلزامي", default="1"),
				f("sabkha_requires_groundwater", "Check", "يلزم مياه جوفية عند السبخة"),
				f("matrix", "Select", "الوسط", opt="soil\ngroundwater"),
				f("source_text", "Small Text", "المصدر"),
				f("exceedance_effect", "Small Text", "أثر التجاوز"),
			],
			autoname="field:code",
			title_field="label_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"Optional Lab Test Def",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("label_ar", "Data", "التسمية", reqd=1, in_list=1),
				f("test_method", "Link", "الطريقة", opt="Test Method"),
				f("is_active", "Check", "فعّال", default="1"),
			],
			autoname="field:code",
			title_field="label_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"Mandatory Sample Test Rule",
			[
				f("sample_kind", "Link", "نوع العينة", opt="Sample Kind", reqd=1, in_list=1),
				f("reference_test", "Link", "الاختبار المرجعي", opt="Reference Test"),
				f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1),
				f("label_ar", "Data", "التسمية"),
				f("requires_attachment", "Check", "يلزم مرفق"),
				f("requires_value", "Check", "يلزم قيمة"),
				f("uom", "Data", "الوحدة"),
				f("sort_order", "Int", "الترتيب"),
			],
			autoname="hash",
			title_field="label_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"Engine Trigger Rule",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("label_ar", "Data", "التسمية", reqd=1),
				f("condition_expr", "Small Text", "الشرط (توثيق)"),
				f("message_ar", "Small Text", "الرسالة"),
				f("action", "Select", "الإجراء", opt="Warn\nRequire Chemical GW\nSuggest Optional Test\nMark Special\nSuggest Chemical Sample"),
				f("optional_test", "Link", "اختبار اختياري", opt="Optional Lab Test Def"),
				f("is_active", "Check", "فعّال", default="1"),
			],
			autoname="hash",
			title_field="label_ar",
			search_fields="code,label_ar",
			permissions=master_perms(),
			track_changes=1,
		),
		dt(
			"Retention Rule",
			[
				f("applies_to", "Select", "ينطبق على", opt="Platform Document\nArchived Sample", reqd=1, in_list=1),
				f("document_type", "Link", "نوع الوثيقة", opt="Document Type"),
				f("sample_kind", "Link", "نوع العينة الأرشيفية", opt="Sample Archive Kind"),
				f("years", "Float", "سنوات"),
				f("days", "Int", "أيام"),
				f("classification", "Link", "التصنيف", opt="Document Classification"),
				f("no_retention", "Check", "اختبار تدميري بلا احتفاظ"),
			],
			autoname="hash",
			permissions=master_perms(),
			track_changes=1,
		),
	]


def settings_and_party():
	return [
		dt(
			"Miyar Settings",
			[
				tab("قواعد التشغيل", "tab_ops"),
				f("max_tests_per_request", "Int", "أقصى اختبارات لكل طلب", reqd=1, default="10"),
				f("proposed_slots", "Int", "عدد المواعيد المقترحة", reqd=1, default="3"),
				f("min_lead_hours", "Int", "أول موعد ≥ ساعات", reqd=1, default="48"),
				col("col_ops_2"),
				f("lab_decision_hours", "Int", "مهلة قرار المختبر (ساعة)", reqd=1, default="12"),
				f("consultant_decision_hours", "Int", "مهلة قرار الاستشاري (ساعة)", reqd=1, default="48"),
				f("quote_validity_days", "Int", "صلاحية عرض السعر (يوم)", default="14"),
				f("lab_timeout_action", "Select", "إجراء انتهاء مهلة المختبر", opt="Expire\nNotify Only", default="Expire"),
				f("auto_approve_consultant", "Check", "اعتماد تلقائي بعد المهلة", default="1"),
				sec("جيوتقني وضريبة"),
				f("min_borehole_depth", "Float", "حد أدنى لعمق الجسة (م)", reqd=1, default="10"),
				f("geofence_meters", "Float", "نطاق التحقق الجغرافي (م)", reqd=1, default="3"),
				f("vat_rate", "Percent", "نسبة الضريبة %", reqd=1, default="15"),
				col("col_geo_2"),
				f("compliance_move_penalty_pct", "Float", "خصم الالتزام لكل متر نقل", default="2"),
				f("compliance_added_bh_penalty_pct", "Float", "خصم الالتزام لكل جسة مضافة", default="4"),
				f("invoice_due_days", "Int", "أيام استحقاق الفاتورة", default="30"),
				tab("محرك وتقييم", "tab_engine"),
				f("engine_policy", "Link", "سياسة مسار المحرك", opt="Engine Policy"),
				f("engine_cloud_cost_ref", "JSON", "مرجع تكلفة السحابة"),
				sec("أبعاد التقييم"),
				f("rating_dimensions", "Table", "أبعاد التقييم", opt="Rating Dimension"),
				tab("دعم وأرشيف", "tab_support"),
				f("support_phone", "Data", "هاتف الدعم", default="920000000"),
				f("support_field_emergency", "Data", "طوارئ ميدانية", default="0550001112"),
				f("support_email", "Data", "بريد الدعم", default="support@miyar.gov.sa"),
				f("support_hours_text", "Data", "ساعات العمل", default="الأحد–الخميس 8–16"),
				col("col_sup_2"),
				f("session_idle_minutes", "Int", "انتهاء الجلسة خمول", default="30"),
				f("saac_expiry_warn_days", "Int", "تنبيه قرب انتهاء SAAC", default="120"),
				f("sample_retention_soil_days", "Int", "احتفاظ تربة (يوم)", default="90"),
				f("sample_retention_concrete_days", "Int", "احتفاظ خرسانة (يوم)", default="180"),
				f("archive_capacity", "Int", "سعة أرشيف العينات"),
			],
			issingle=1,
			track_changes=1,
			permissions=admin_full()
			+ [readp(r) for r in (*PARTIES, SUP, SPT)],
		),
		dt(
			"Organization",
			[
				tab("بيانات المنشأة", "tab_org"),
				f("organization_name", "Data", "اسم المنشأة", reqd=1, in_list=1, in_global_search=1, bold=1),
				f("organization_type", "Link", "النوع", opt="Organization Type", reqd=1, in_list=1, in_std=1),
				f("cr", "Data", "السجل التجاري", reqd=1, unique=1, in_list=1, length=10),
				f("logo", "Attach Image", "الشعار"),
				col("col_org_2"),
				f("cr_status", "Data", "حالة السجل"),
				f("cr_activity", "Data", "النشاط"),
				f("cr_issued_on", "Data", "تاريخ الإصدار (واثق)"),
				f("cr_issued_on_g", "Date", "تاريخ الإصدار الميلادي"),
				f("license", "Data", "الرخصة البلدية"),
				f("territory", "Link", "المدينة / المنطقة", opt="Territory", reqd=1, in_std=1),
				f("district", "Data", "الحي"),
				sec("تواصل"),
				f("phone", "Data", "الهاتف"),
				f("email", "Data", "البريد"),
				f("website", "Data", "الموقع"),
				col("col_contact_2"),
				f("address_html", "Small Text", "العنوان"),
				f("about", "Text Editor", "نبذة"),
				tab("اعتماد ودليل", "tab_dir"),
				f("saac", "Table", "اعتماد SAAC", opt="SAAC Accreditation"),
				f("specialties", "Table", "التخصصات", opt="Organization Specialty"),
				sec("الظهور"),
				f("directory_status", "Select", "الظهور", opt=DIR_STS, default="STS04", in_list=1, in_std=1),
				f("active", "Check", "الحساب فعّال", default="1", in_list=1),
				f("featured", "Check", "مميّز في الدليل"),
				col("col_dir_2"),
				f("since_year", "Int", "منذ سنة"),
				f("employee_count", "Int", "عدد الموظفين (تعريفي)"),
				f("rating", "Float", "التقييم", ro=1, in_list=1),
				f("reviews", "Int", "عدد التقييمات المعتمدة", ro=1),
				f("on_time", "Percent", "الالتزام بالموعد %", ro=1),
				f("auto_approvals", "Int", "اعتمادات تلقائية", ro=1),
			],
			autoname="ORG-.#####",
			title_field="organization_name",
			search_fields="organization_name,cr",
			image_field="logo",
			track_changes=1,
			show_name_in_global_search=1,
			permissions=admin_full()
			+ [
				readp(VISITOR),
				rwc(C_P, delete=0),
				readp(C_E),
				rwc(L_P, delete=0),
				readp(L_E),
				rwc(K_P, delete=0),
				readp(K_E),
				readp(SUP),
				P(SPT, read=1, write=1, report=1, export=1, print=1),
			],
			links=[
				{"link_doctype": "Organization User", "link_fieldname": "organization"},
				{"link_doctype": "Lab Catalog Item", "link_fieldname": "lab"},
				{"link_doctype": "Service Contract", "link_fieldname": "lab"},
			],
		),
		dt(
			"Organization Registration",
			[
				f("cr", "Data", "السجل التجاري", reqd=1, in_list=1, length=10),
				f("organization_type", "Link", "النوع", opt="Organization Type", reqd=1, in_std=1),
				f("organization_name", "Data", "اسم المنشأة", in_list=1),
				f("status", "Select", "الحالة", opt=REG_STS, default="Draft", in_list=1, in_std=1),
				col("col_reg_2"),
				f("wathq_payload", "JSON", "استجابة واثق", ro=1),
				f("organization", "Link", "المنشأة الناتجة", opt="Organization"),
				f("activated_at", "Datetime", "وقت التفعيل", ro=1),
				sec("المفوّض الرئيسي"),
				f("principal_name", "Data", "اسم المفوّض", reqd=1),
				f("principal_national_id", "Data", "الهوية", reqd=1, length=10),
				col("col_pr_2"),
				f("principal_mobile", "Data", "الجوال", reqd=1),
				f("principal_email", "Data", "البريد", reqd=1),
				sec("اعتماد ومراجعة"),
				f("saac_number", "Data", "رقم SAAC"),
				f("agreed_terms", "Check", "موافقة الشروط", reqd=1),
				f("reject_reason", "Small Text", "سبب الرفض"),
				f("clarification_note", "Small Text", "طلب مستندات"),
			],
			autoname="REG-.YYYY.-.####",
			is_submittable=1,
			title_field="organization_name",
			search_fields="cr,organization_name,principal_name",
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [
				rwc(VISITOR, delete=0),
				P(SPT, read=1, write=1, submit=1, report=1, export=1, print=1),
				readp(SUP),
			],
		),
		dt(
			"Organization User",
			[
				f("organization", "Link", "المنشأة", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("user", "Link", "المستخدم", opt="User", reqd=1, unique=1, in_list=1),
				f("position", "Select", "الصفة", opt="Principal\nEmployee", reqd=1, in_list=1),
				f("can_delegate", "Check", "صلاحية التفويض الأصلية"),
				f("national_id", "Data", "الهوية", length=10),
				f("is_active", "Check", "نشط", default="1", in_list=1),
			],
			autoname="hash",
			search_fields="user,organization",
			track_changes=1,
			permissions=admin_full()
			+ [
				rwc(C_P, delete=0),
				readp(C_E),
				rwc(L_P, delete=0),
				readp(L_E),
				rwc(K_P, delete=0),
				readp(K_E),
				readp(SUP),
				rwc(SPT, delete=0),
			],
		),
		dt(
			"User Notification Pref",
			[
				f("user", "Link", "المستخدم", opt="User", reqd=1, unique=1, in_list=1),
				f("sms", "Check", "رسائل SMS", default="1"),
				f("email", "Check", "البريد", default="1"),
				f("push", "Check", "إشعارات فورية"),
				f("digest", "Check", "ملخص صباحي", default="1"),
			],
			autoname="field:user",
			permissions=admin_full() + [rwc(r, delete=0) for r in (*PARTIES, SUP, SPT, VISITOR)],
		),
		dt(
			"User Preference",
			[
				f("user", "Link", "المستخدم", opt="User", reqd=1, unique=1, in_list=1),
				f("calendar", "Select", "التقويم", opt="both\ng\nh", default="both"),
				f("density", "Select", "كثافة العرض", opt="comfortable\ncompact", default="comfortable"),
				f("home", "Select", "الصفحة الرئيسية", opt="dash\nreq", default="dash"),
				f("language", "Data", "اللغة", default="ar", ro=1),
			],
			autoname="field:user",
			permissions=admin_full() + [rwc(r, delete=0) for r in (*PARTIES, SUP, SPT, VISITOR)],
		),
	]


def catalog_and_commercial():
	ref_admin = admin_full() + [readp(r) for r in (*PARTIES, SUP, SPT)]
	return [
		dt(
			"Reference Test",
			[
				f("code", "Data", "الرمز", unique=1, in_list=1, in_std=1, desc="مثل RT-PROCTOR — إن فُرغ يُولَّد RT-.#####"),
				f("test_name_ar", "Data", "الاسم عربي", reqd=1, in_list=1, in_global_search=1),
				f("test_name_en", "Data", "الاسم إنجليزي", reqd=1, in_list=1),
				f("item_group", "Link", "التصنيف", opt="Item Group", reqd=1, in_std=1),
				col("col_rt_2"),
				f("item", "Link", "الصنف", opt="Item", ro=1),
				f("is_geotech", "Check", "دراسة جيوتقنية"),
				f("allow_external_report", "Check", "يسمح بتقرير خارجي"),
				f("is_active", "Check", "فعّال", default="1", in_list=1),
				sec("وحدات وطرق"),
				f("units", "Table", "الوحدات المتاحة", opt="Reference Test UOM"),
				f("methods", "Table", "الطرق", opt="Reference Test Method"),
				sec("حقول النتيجة"),
				f("result_fields", "Table", "حقول النتيجة", opt="Reference Test Result Field"),
			],
			autoname="RT-.#####",
			title_field="test_name_ar",
			search_fields="test_name_ar,test_name_en",
			track_changes=1,
			permissions=ref_admin,
		),
		dt(
			"Acceptance Limit",
			[
				f("reference_test", "Link", "الاختبار", opt="Reference Test", reqd=1, in_list=1, in_std=1),
				f("field_key", "Data", "حقل النتيجة", reqd=1, in_list=1),
				f("rule_text", "Small Text", "نص القاعدة", reqd=1),
				f("reference_text", "Data", "المرجع"),
				f("knowledge_version", "Link", "إصدار المعرفة", opt="Knowledge Version"),
			],
			autoname="hash",
			permissions=ref_admin,
			track_changes=1,
		),
		dt(
			"Method Sheet",
			[
				f("reference_test", "Link", "الاختبار", opt="Reference Test", reqd=1, in_list=1),
				f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1, in_list=1),
				f("title", "Data", "العنوان", reqd=1),
				f("form_code", "Data", "رمز النموذج", in_list=1),
				sec("إجراء"),
				f("procedure", "Table", "الخطوات", opt="Method Step"),
				f("specimen_desc", "Small Text", "وصف العينة"),
				f("specimen_fields", "Table", "حقول العينة", opt="Method Specimen Field"),
				f("equipment_types", "Table", "أنواع المعدات", opt="Method Equipment Type"),
				sec("بيئة وتقرير"),
				f("environment", "Data", "البيئة"),
				f("uncertainty", "Small Text", "اللايقين"),
				f("reporting", "Small Text", "التقرير"),
				f("acceptance", "Small Text", "القبول"),
			],
			autoname="MS-.#####",
			title_field="title",
			search_fields="form_code,title",
			track_changes=1,
			permissions=admin_full()
			+ [readp(r) for r in (*CONTRACTORS, *CONSULTANTS, SUP, SPT)]
			+ [rwc(L_P, delete=0), rwc(L_E, delete=0)],
		),
		dt(
			"Lab Catalog Item",
			[
				f("lab", "Link", "المختبر", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("reference_test", "Link", "الاختبار", opt="Reference Test", reqd=1, in_list=1, in_std=1),
				f("uom", "Link", "الوحدة", opt="UOM"),
				f("status", "Select", "الحالة", opt=CAT_STS, default="STS03", in_list=1, in_std=1),
				col("col_cat_2"),
				f("base_price", "Currency", "السعر الأساسي", opt="SAR", in_list=1),
				f("sla_days", "Int", "مدة التنفيذ (يوم)"),
				sec("الطرق المختارة"),
				f("methods", "Table", "الطرق", opt="Catalog Method"),
			],
			autoname="CAT-.#####",
			search_fields="lab,reference_test",
			track_changes=1,
			permissions=admin_full(delete=0)
			+ [
				rwc(L_P, delete=0),
				readp(L_E),
				readp(SUP),
				readp(SPT),
			],
		),
		dt(
			"Miyar Quote",
			[
				f("contractor", "Link", "المقاول", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("lab", "Link", "المختبر", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("consultant", "Link", "الاستشاري", opt="Organization", reqd=1, in_std=1),
				f("status", "Select", "الحالة", opt=QUOTE_STS, default="Pending", in_list=1, in_std=1),
				col("col_q_2"),
				f("project_name", "Data", "المشروع", reqd=1, in_list=1),
				f("city", "Link", "المدينة", opt="Territory"),
				f("payment_term", "Link", "الدفع", opt="Payment Term Code", reqd=1),
				f("valid_until", "Date", "صالح حتى"),
				sec("خدمات وبنود"),
				f("services", "Table", "الخدمات", opt="Quote Service"),
				f("items", "Table", "البنود", opt="Miyar Quote Item"),
				sec("ملاحظات وقرار"),
				f("notes", "Small Text", "ملاحظات المقاول"),
				f("lab_notes", "Small Text", "ملاحظات المختبر"),
				f("reject_reason", "Small Text", "سبب الرفض"),
				col("col_qdec_2"),
				f("quoted_at", "Datetime", "تاريخ الرد"),
				f("decided_at", "Datetime", "تاريخ القرار"),
				f("otp_verified", "Check", "توقيع OTP"),
				f("service_contract", "Link", "العقد الناتج", opt="Service Contract"),
			],
			autoname="QT-.YYYY.-.####",
			is_submittable=1,
			title_field="project_name",
			search_fields="project_name,contractor,lab",
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [
				rwc(C_P, delete=0, submit=1),
				rwc(C_E, delete=0, submit=1),
				P(L_P, read=1, write=1, report=1, export=1, print=1),
				readp(L_E),
				readp(K_P),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
		),
		dt(
			"Service Contract",
			[
				f("contractor", "Link", "المقاول", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("lab", "Link", "المختبر", opt="Organization", reqd=1, in_list=1, in_std=1),
				f("consultant", "Link", "الاستشاري", opt="Organization", reqd=1, in_list=1),
				f("is_active", "Check", "فعّال", default="1", in_list=1, in_std=1),
				col("col_sc_2"),
				f("project_name", "Data", "المشروع", reqd=1, in_list=1, in_global_search=1),
				f("city", "Link", "المدينة", opt="Territory"),
				f("payment_term", "Link", "الدفع", opt="Payment Term Code", reqd=1),
				f("quote", "Link", "العرض المصدر", opt="Miyar Quote"),
				sec("خدمات وبنود مثبتة"),
				f("services", "Table", "الخدمات", opt="Contract Service"),
				f("items", "Table", "البنود", opt="Contract Item"),
				sec("مدة وملف"),
				f("started_on", "Date", "تاريخ البدء"),
				f("ended_on", "Date", "تاريخ الانتهاء"),
				f("contract_file", "Attach", "ملف العقد"),
			],
			autoname="CNT-.YYYY.-.###",
			is_submittable=1,
			title_field="project_name",
			search_fields="project_name,contractor,lab,consultant",
			track_changes=1,
			show_name_in_global_search=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [readp(r) for r in (*PARTIES, SUP, SPT)],
			links=[
				{"link_doctype": "Test Request", "link_fieldname": "service_contract"},
				{"link_doctype": "Laboratory Invoice", "link_fieldname": "service_contract"},
			],
		),
	]


def operations():
	req_perms = admin_full(submit=1, cancel=1) + [
		rwc(C_P, delete=0, submit=1, cancel=1),
		rwc(C_E, delete=0, submit=1, cancel=1),
		P(L_P, read=1, write=1, report=1, export=1, print=1),
		readp(L_E),
		readp(K_P),
		readp(K_E),
		readp(SUP),
		P(SPT, read=1, cancel=1, report=1, export=1, print=1),
	]
	return [
		dt(
			"Test Request",
			[
				f("naming_series", "Select", "الترقيم", opt="TST-DRAFT-.\nTST-.YYYY.-.", default="TST-DRAFT-."),
				f("status", "Select", "الحالة", opt=REQ_STS, default="STS09", in_list=1, in_std=1),
				f("service_contract", "Link", "العقد", opt="Service Contract", reqd=1, in_std=1),
				f("service_type", "Link", "نوع الخدمة", opt="Service Type", reqd=1, in_list=1, in_std=1),
				col("col_tr_2"),
				f("contractor", "Link", "المقاول", opt="Organization", fetch="service_contract.contractor", ro=1, in_list=1),
				f("lab", "Link", "المختبر", opt="Organization", fetch="service_contract.lab", ro=1, in_list=1),
				f("consultant", "Link", "الاستشاري", opt="Organization", fetch="service_contract.consultant", ro=1),
				f("priority", "Link", "الأولوية", opt="Priority"),
				sec("مشروع وموقع"),
				f("project_name", "Data", "المشروع", in_list=1, in_global_search=1),
				f("category", "Link", "تصنيف الاختبارات", opt="Item Group", in_std=1),
				f("city", "Link", "المدينة", opt="Territory"),
				f("location", "Small Text", "وصف الموقع", reqd=1),
				col("col_loc_2"),
				f("geo_lat", "Float", "خط العرض"),
				f("geo_lng", "Float", "خط الطول"),
				f("notes", "Small Text", "ملاحظات"),
				f("delegate", "Link", "المفوَّض الحالي", opt="User"),
				tab("مواعيد ومهل", "tab_slots"),
				f("submitted_at", "Datetime", "وقت الإرسال"),
				f("lab_deadline_at", "Datetime", "مهلة رد المختبر"),
				f("chosen_slot_date", "Date", "الموعد المعتمد"),
				f("chosen_slot_from", "Time", "من"),
				f("chosen_slot_to", "Time", "إلى"),
				f("reject_reason", "Small Text", "سبب الرفض"),
				sec("المواعيد المقترحة"),
				f("slots", "Table", "المواعيد المقترحة", opt="Request Time Slot"),
				tab("لقطة وروابط", "tab_snap"),
				f("parent_request", "Link", "الطلب الأصل", opt="Test Request"),
				f("retest_of", "Link", "بند الاختبار الأصل", opt="Test Line"),
				f("study", "Link", "الدراسة", opt="Geotechnical Study"),
				f("rules_snapshot", "Table", "لقطة القواعد", opt="Request Rules Snapshot"),
				tab("مرفقات وسجل", "tab_hist"),
				f("attachments", "Table", "مرفقات الطلب", opt="Request Attachment"),
				f("history", "Table", "سجل الطلب", opt="Request History"),
			],
			autoname="naming_series:",
			is_submittable=1,
			title_field="project_name",
			search_fields="project_name,contractor,lab,status",
			track_changes=1,
			show_name_in_global_search=1,
			permissions=req_perms,
			links=[
				{"link_doctype": "Test Line", "link_fieldname": "test_request"},
				{"link_doctype": "Geotechnical Study", "link_fieldname": "test_request"},
				{"link_doctype": "Laboratory Invoice", "link_fieldname": "test_request"},
				{"link_doctype": "Delegation", "link_fieldname": "test_request"},
			],
		),
		dt(
			"Test Line",
			[
				f("test_request", "Link", "الطلب", opt="Test Request", reqd=1, in_list=1, in_std=1),
				f("reference_test", "Link", "الاختبار", opt="Reference Test", reqd=1, in_list=1),
				f("test_method", "Link", "الطريقة", opt="Test Method", reqd=1),
				f("status", "Select", "الحالة", opt=TL_STS, default="STS17", in_list=1, in_std=1),
				col("col_tl_2"),
				f("uom", "Link", "الوحدة", opt="UOM"),
				f("price", "Currency", "السعر", opt="SAR"),
				f("sla_days", "Int", "SLA"),
				f("auto_approved", "Check", "اعتماد تلقائي"),
				sec("عينة وتنفيذ"),
				f("sample_id", "Data", "رقم العينة الميدانية"),
				f("sample_depth", "Float", "العمق (م)"),
				f("technician", "Link", "الفني", opt="User"),
				f("sample_received_at", "Datetime", "استلام العينة"),
				col("col_samp_2"),
				f("geo_verified", "Check", "تحقق جغرافي"),
				f("geo_distance_m", "Float", "المسافة (م)"),
				f("contractor_confirmed", "Check", "تأكيد المقاول"),
				f("contractor_confirmed_at", "Datetime", "وقت التأكيد"),
				sec("بيئة"),
				f("lab_temperature_c", "Float", "حرارة المختبر °م"),
				f("lab_humidity_pct", "Float", "رطوبة المختبر %"),
				f("field_weather", "Link", "طقس الموقع", opt="Weather Condition"),
				tab("نتائج ومعدات", "tab_res"),
				f("result_values", "Table", "النتائج", opt="Test Result Value"),
				f("specimen_values", "Table", "قياسات العينة", opt="Test Specimen Value"),
				f("equipment_used", "Table", "المعدات المستخدمة", opt="Test Equipment Use"),
				f("photos", "Table", "الأدلة", opt="Test Photo Link"),
				tab("مخرج ومهل", "tab_out"),
				f("started_at", "Datetime", "بدء التنفيذ"),
				f("submitted_at", "Datetime", "رفع المخرج"),
				f("decided_at", "Datetime", "قرار الاستشاري"),
				f("execution_deadline_at", "Datetime", "مهلة التنفيذ"),
				f("consultant_deadline_at", "Datetime", "مهلة الاستشاري"),
				f("delay_hours", "Int", "ساعات التأخر عن الموعد"),
				f("report_file", "Attach", "تقرير PDF"),
				f("notes", "Small Text", "ملاحظات المختبر"),
				f("reject_reason", "Small Text", "سبب رفض المخرج"),
				f("delegate", "Link", "المفوَّض", opt="User"),
			],
			autoname="TL-.#####",
			is_submittable=1,
			search_fields="test_request,reference_test,status",
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [
				readp(C_P),
				readp(C_E),
				rwc(L_P, delete=0, submit=1),
				rwc(L_E, delete=0, submit=1),
				P(K_P, read=1, write=1, report=1, export=1, print=1),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
		),
		dt(
			"Geotechnical Study",
			[
				f("test_request", "Link", "الطلب", opt="Test Request", reqd=1, unique=1, in_list=1),
				f("phase", "Int", "المرحلة", default="1", ro=1, in_list=1),
				f("knowledge_version", "Link", "إصدار المعرفة المجمَّد", opt="Knowledge Version"),
				f("template", "Link", "قالب التقرير", opt="Report Template"),
				tab("بيانات أولية", "tab_prelim"),
				f("deed_file", "Attach", "القرار المساحي"),
				f("ocr_payload", "JSON", "استخراج OCR"),
				f("parcel", "Data", "قطعة"),
				f("plan_no", "Data", "مخطط"),
				f("district", "Data", "حي"),
				col("col_pre_2"),
				f("city", "Link", "مدينة", opt="Territory"),
				f("region", "Link", "منطقة", opt="Territory"),
				f("deed_no", "Data", "رقم الصك"),
				f("deed_date", "Data", "تاريخ الصك"),
				f("plot_area", "Float", "المساحة قرار"),
				f("computed_area", "Float", "المساحة محسوبة"),
				f("boundary_ok", "Check", "الحدود مطابقة"),
				sec("مالك ومشروع"),
				f("owner_name", "Data", "المالك"),
				f("owner_id", "Data", "هوية المالك", length=10),
				f("building_type", "Link", "نوع المشروع", opt="Building Type"),
				f("structure_type", "Link", "الهيكل", opt="Structure Type"),
				col("col_proj_2"),
				f("floors", "Int", "الأدوار"),
				f("built_area", "Float", "المساحة المبنية"),
				f("foundation_type", "Link", "نوع التأسيس", opt="Foundation Type"),
				f("foundation_depth", "Float", "عمق التأسيس (م)"),
				f("prior_info", "Check", "معلومات سابقة"),
				f("neighbors", "Check", "جوار"),
				f("permit_no", "Data", "رقم الرخصة"),
				f("prelim_approved", "Check", "اعتماد الاستشاري للأولية"),
				f("review_notes", "Small Text", "ملاحظات المراجعة"),
				sec("ظروف ومضلع"),
				f("site_conditions", "Table", "ظروف الموقع", opt="Study Site Condition"),
				f("polygon", "Table", "المضلع", opt="Study Polygon Point"),
				tab("خطة الاستكشاف", "tab_plan"),
				f("engine_count", "Int", "عدد الجسات المقترح", ro=1),
				f("engine_depth", "Float", "العمق المقترح", ro=1),
				f("engine_spacing", "Float", "التباعد المقترح", ro=1),
				f("engine_special", "Check", "دراسة خاصة", ro=1),
				f("engine_ref", "Small Text", "مرجع المحرك"),
				f("table_21_row", "Link", "صف Table 2.1", opt="SBC Table 21 Row", ro=1),
				f("engine_basis", "Table", "أساس التوصية", opt="Engine Basis Line"),
				sec("اعتماد الخطة"),
				f("plan_approved", "Check", "اعتماد الخطة"),
				f("plan_approved_at", "Datetime", "تاريخ الاعتماد"),
				f("plan_justification", "Small Text", "مبرر الانحراف"),
				f("field_plan_reviewed", "Check", "اعتماد الخطة الميدانية"),
				f("field_plan_reason", "Small Text", "مبرر النقل/الإضافة"),
				f("field_plan_ack", "Check", "إقرار التنسيق مع الاستشاري"),
				f("compliance_pct", "Percent", "الالتزام %", ro=1),
				f("field_approved", "Check", "اكتمال الحقلي"),
				tab("كيميائية", "tab_chem"),
				f("chemical_sample", "Link", "العينة المختارة", opt="Field Sample"),
				f("chemical_suggested_sample", "Link", "مقترح المحرك", opt="Field Sample", ro=1),
				f("chemical_override_reason", "Small Text", "سبب تجاوز المقترح"),
				f("chemical_results", "Table", "النتائج", opt="Chemical Result"),
				f("chemical_done", "Check", "اعتماد الكيميائية"),
				f("chemical_partial_reason", "Small Text", "إكمال جزئي"),
				tab("تحليل", "tab_an"),
				f("computed_fields", "Table", "حسابية", opt="Analysis Computed"),
				f("analytical_fields", "Table", "تحليلية", opt="Analysis Key Value"),
				f("recommendations", "Table", "توصيات", opt="Analysis Key Value"),
				f("manual_fields", "Table", "يدوية مسموحة", opt="Analysis Key Value"),
				f("analysis_attachments", "Table", "مرفقات", opt="Analysis Attachment"),
				f("analysis_done", "Check", "اكتمال التحليل"),
				tab("تقرير", "tab_rep"),
				f("report_previewed", "Check", "عُرضت المعاينة"),
				f("report_approved", "Check", "معتمد"),
				f("report_approved_at", "Datetime", "تاريخ الاعتماد"),
				f("report_reject_reason", "Small Text", "سبب الرفض"),
				f("report_file", "Attach", "الملف الرسمي"),
				f("report_hash", "Data", "بصمة", ro=1),
			],
			autoname="GT-.#####",
			is_submittable=1,
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [
				rwc(C_P, delete=0),
				rwc(C_E, delete=0),
				rwc(L_P, delete=0),
				rwc(L_E, delete=0),
				rwc(K_P, delete=0),
				rwc(K_E, delete=0),
				readp(SUP),
				readp(SPT),
			],
			links=[
				{"link_doctype": "Borehole", "link_fieldname": "study"},
			],
		),
		dt(
			"Borehole",
			[
				f("study", "Link", "الدراسة", opt="Geotechnical Study", reqd=1, in_list=1, in_std=1),
				f("code", "Data", "الرمز", in_list=1),
				f("status", "Select", "الحالة", opt=BH_STS, default="Ready", in_list=1, in_std=1),
				f("added_by_lab", "Check", "أضافها المختبر"),
				sec("إحداثيات"),
				f("approved_n", "Float", "شمال معتمد"),
				f("approved_e", "Float", "شرق معتمد"),
				f("operational_n", "Float", "شمال تشغيلي"),
				f("operational_e", "Float", "شرق تشغيلي"),
				col("col_bh_2"),
				f("actual_n", "Float", "شمال GPS"),
				f("actual_e", "Float", "شرق GPS"),
				f("moved_m", "Float", "النقل (م)"),
				f("geo_distance_m", "Float", "بُعد GPS عن التشغيلي"),
				sec("أعماق"),
				f("approved_depth", "Float", "العمق المعتمد"),
				f("executed_depth", "Float", "المنفَّذ"),
				f("not_reached_reason", "Small Text", "سبب عدم بلوغ العمق"),
				f("added_reason", "Small Text", "سبب الإضافة"),
				tab("رأس الجسة", "tab_head"),
				f("borehole_method", "Link", "طريقة الحفر", opt="Borehole Method"),
				f("rig", "Data", "الحفّار"),
				f("diameter_mm", "Float", "القطر مم"),
				f("casing_m", "Float", "التغليف م"),
				col("col_head_2"),
				f("ground_level", "Float", "منسوب الأرض"),
				f("water_instant", "Float", "مياه لحظي"),
				f("water_24h", "Float", "مياه 24س"),
				f("work_date", "Date", "تاريخ التنفيذ"),
				f("weather", "Link", "الطقس", opt="Weather Condition"),
				f("technician", "Link", "الفني", opt="User"),
				sec("صور"),
				f("photos", "Table", "صور", opt="Borehole Photo Link"),
			],
			autoname="format:{study}-BH-.##",
			title_field="code",
			track_changes=1,
			permissions=admin_full()
			+ [
				readp(C_P),
				readp(C_E),
				rwc(L_P, delete=0),
				rwc(L_E, delete=0),
				readp(K_P),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
			links=[
				{"link_doctype": "Borehole Layer", "link_fieldname": "borehole"},
				{"link_doctype": "Field Sample", "link_fieldname": "borehole"},
			],
		),
		dt(
			"Borehole Layer",
			[
				f("borehole", "Link", "الجسة", opt="Borehole", reqd=1, in_list=1, in_std=1),
				f("layer_code", "Data", "رمز الطبقة", in_list=1),
				f("depth_from", "Float", "من (م)", reqd=1),
				f("depth_to", "Float", "إلى (م)", reqd=1),
				col("col_ly_2"),
				f("uscs", "Link", "USCS حقلي", opt="USCS Classification"),
				f("gradation", "Link", "التدرج", opt="Gradation"),
				f("color", "Link", "اللون", opt="Soil Color"),
				f("moisture", "Link", "الرطوبة", opt="Moisture Description"),
				sec("SPT"),
				f("spt_n1", "Int", "N1"),
				f("spt_n2", "Int", "N2"),
				f("spt_n3", "Int", "N3"),
				f("n_value", "Int", "N = N2+N3", ro=1, in_list=1),
				col("col_spt_2"),
				f("rec_pct", "Percent", "REC %"),
				f("rqd_pct", "Percent", "RQD %"),
				f("description", "Small Text", "الوصف"),
				f("offsite_reason", "Small Text", "سبب التنفيذ خارج الموقع"),
				f("photo", "Attach", "صورة"),
			],
			autoname="hash",
			track_changes=1,
			permissions=admin_full()
			+ [
				readp(C_P),
				readp(C_E),
				rwc(L_P, delete=0),
				rwc(L_E, delete=0),
				readp(K_P),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
		),
		dt(
			"Field Sample",
			[
				f("borehole", "Link", "الجسة", opt="Borehole", reqd=1, in_list=1, in_std=1),
				f("layer", "Link", "الطبقة", opt="Borehole Layer"),
				f("sample_code", "Data", "رمز العينة", in_list=1),
				f("lab_status", "Select", "حالة المعمل", opt=FS_STS, default="Ready", in_list=1),
				col("col_fs_2"),
				f("sample_type", "Link", "نوع العينة", opt="Sample Type"),
				f("sample_kind", "Link", "صنف العينة", opt="Sample Kind"),
				f("depth_from", "Float", "من (م)"),
				f("depth_to", "Float", "إلى (م)"),
				f("field_uscs", "Link", "USCS حقلي", opt="USCS Classification"),
				f("lab_uscs", "Link", "USCS نهائي", opt="USCS Classification"),
				sec("اختبارات"),
				f("tests", "Table", "الاختبارات", opt="Sample Test Row"),
			],
			autoname="FS-.#####",
			title_field="sample_code",
			track_changes=1,
			permissions=admin_full()
			+ [
				readp(C_P),
				readp(C_E),
				rwc(L_P, delete=0),
				rwc(L_E, delete=0),
				readp(K_P),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
		),
	]


def rest():
	return [
		dt(
			"Lab Rating",
			[
				f("service_contract", "Link", "العقد", opt="Service Contract", reqd=1, in_list=1),
				f("lab", "Link", "المختبر", opt="Organization", fetch="service_contract.lab", in_list=1),
				f("contractor", "Link", "المقاول", opt="Organization", fetch="service_contract.contractor"),
				f("status", "Select", "الحالة", opt=RTG_STS, default="STS06", in_list=1, in_std=1),
				f("comment", "Small Text", "تعليق"),
				f("scores", "Table", "الدرجات", opt="Rating Score"),
			],
			autoname="RTG-.#####",
			track_changes=1,
			permissions=admin_full()
			+ [
				rwc(C_P, delete=0),
				rwc(C_E, delete=0),
				readp(L_P),
				readp(L_E),
				readp(SUP),
				P(SPT, read=1, write=1, report=1, export=1),
			],
		),
		dt(
			"Delegation",
			[
				f("delegation_type", "Select", "النوع", opt="Direct\nIndirect", reqd=1, in_list=1),
				f("scope", "Select", "النطاق", opt="Request\nTest", reqd=1),
				f("status", "Select", "الحالة", opt=DEL_STS, default="STS22", in_list=1, in_std=1),
				f("test_request", "Link", "الطلب", opt="Test Request", reqd=1, in_list=1, in_std=1),
				col("col_del_2"),
				f("test_line", "Link", "بند الاختبار", opt="Test Line"),
				f("from_user", "Link", "من", opt="User", reqd=1),
				f("to_user", "Link", "إلى", opt="User", reqd=1, in_list=1),
				f("decided_at", "Datetime", "تاريخ القرار"),
			],
			autoname="DEL-.#####",
			is_submittable=1,
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [rwc(r, delete=0, submit=1, cancel=1) for r in PARTIES]
			+ [readp(SUP), readp(SPT)],
		),
		dt(
			"Calibration Record",
			[
				f("asset", "Link", "الأصل", opt="Asset", reqd=1, in_list=1, in_std=1),
				f("calibrated_on", "Date", "تاريخ المعايرة", reqd=1, in_list=1),
				f("due_on", "Date", "الاستحقاق"),
				f("certificate_no", "Data", "رقم الشهادة"),
				f("provider", "Data", "الجهة"),
				f("file", "Attach", "الملف"),
				f("sets_status_valid", "Check", "تعيين الحالة صالح", default="1"),
			],
			autoname="CAL-.#####",
			track_changes=1,
			permissions=admin_full()
			+ [rwc(L_P, delete=0), rwc(L_E, delete=0)]
			+ [readp(r) for r in (C_P, C_E, K_P, K_E, SUP, SPT)],
		),
		dt(
			"Archived Sample",
			[
				f("lab", "Link", "المختبر", opt="Organization", in_list=1, in_std=1),
				f("archive_kind", "Link", "النوع", opt="Sample Archive Kind", in_list=1),
				f("designation", "Data", "التسمية", in_list=1),
				f("test_request", "Link", "الطلب", opt="Test Request"),
				col("col_as_2"),
				f("test_line", "Link", "البند", opt="Test Line"),
				f("borehole", "Link", "الجسة", opt="Borehole"),
				f("collected_at", "Datetime", "وقت الجمع"),
				f("collected_by", "Data", "جمعها"),
				sec("موقع وكتلة"),
				f("lat", "Float", "عرض"),
				f("lng", "Float", "طول"),
				f("mass_g", "Float", "الكتلة غ"),
				f("condition", "Link", "الحالة الفيزيائية", opt="Sample Condition"),
				col("col_asb_2"),
				f("storage", "Data", "التخزين"),
				f("retention_until", "Date", "الاحتفاظ حتى"),
				f("seal_no", "Data", "رقم الختم"),
				f("status", "Data", "الحالة من الحيازة", ro=1),
				sec("أبعاد وحيازة"),
				f("dimensions", "Table", "الأبعاد", opt="Sample Dimension"),
				f("custody", "Table", "الحيازة", opt="Custody Event"),
				f("photos", "Table", "صور", opt="Archived Sample Photo"),
			],
			autoname="SMP-.YYYY.-.####",
			title_field="designation",
			track_changes=1,
			permissions=admin_full()
			+ [readp(r) for r in CONTRACTORS]
			+ [rwc(L_P, delete=0), rwc(L_E, delete=0)]
			+ [readp(r) for r in (*CONSULTANTS, SUP, SPT)],
		),
		dt(
			"Photo Evidence",
			[
				f("file", "Attach Image", "الملف"),
				f("photo_kind", "Link", "النوع", opt="Photo Kind"),
				f("caption", "Small Text", "الوصف"),
				f("taken_at", "Datetime", "وقت الالتقاط"),
				f("lat", "Float", "عرض"),
				f("lng", "Float", "طول"),
				f("accuracy_m", "Float", "دقة م"),
				f("device", "Data", "الجهاز"),
				f("content_hash", "Data", "بصمة sha256", ro=1),
				sec("ربط"),
				f("test_request", "Link", "الطلب", opt="Test Request"),
				f("test_line", "Link", "البند", opt="Test Line"),
				f("archived_sample", "Link", "عينة أرشيف", opt="Archived Sample"),
				f("borehole", "Link", "الجسة", opt="Borehole"),
			],
			autoname="PH-.#####",
			track_changes=1,
			permissions=admin_full()
			+ [readp(r) for r in CONTRACTORS]
			+ [rwc(L_P, delete=0), rwc(L_E, delete=0)]
			+ [readp(r) for r in (*CONSULTANTS, SUP, SPT)],
		),
		dt(
			"Laboratory Invoice",
			[
				f("service_contract", "Link", "العقد", opt="Service Contract", in_std=1),
				f("test_request", "Link", "الطلب", opt="Test Request", in_list=1),
				f("seller_lab", "Link", "البائع (مختبر)", opt="Organization", in_list=1),
				f("buyer_contractor", "Link", "المشتري (مقاول)", opt="Organization", in_list=1),
				col("col_inv_2"),
				f("status", "Select", "الحالة", opt=INV_STS, default="Draft", in_list=1, in_std=1),
				f("seller_vat_no", "Data", "الرقم الضريبي للبائع"),
				f("buyer_vat_no", "Data", "الرقم الضريبي للمشتري"),
				f("payment_channel", "Link", "قناة السداد", opt="Payment Channel"),
				sec("مبالغ"),
				f("items", "Table", "البنود", opt="Invoice Item"),
				f("amount", "Currency", "قبل الضريبة", opt="SAR"),
				f("vat_rate", "Percent", "نسبة الضريبة"),
				f("vat_amount", "Currency", "الضريبة", opt="SAR"),
				f("grand_total", "Currency", "الإجمالي", opt="SAR", in_list=1),
				sec("تواريخ وZATCA"),
				f("issued_at", "Datetime", "تاريخ الإصدار"),
				f("due_at", "Date", "الاستحقاق"),
				f("paid_at", "Datetime", "وقت السداد"),
				f("zatca_uuid", "Data", "ZATCA UUID"),
				f("zatca_qr", "Data", "ZATCA QR"),
				f("invoice_file", "Attach", "ملف الفاتورة"),
				f("blocks_certificate", "Check", "يمنع شهادة الإتمام", ro=1),
			],
			autoname="INV-.YYYY.-.####",
			is_submittable=1,
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [readp(r) for r in (*CONTRACTORS, *LABS, SUP, SPT)],
		),
		dt(
			"Platform Document",
			[
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("document_type", "Link", "النوع", opt="Document Type", in_std=1),
				f("classification", "Link", "التصنيف", opt="Document Classification"),
				f("file", "Attach", "الملف"),
				col("col_pd_2"),
				f("test_request", "Link", "الطلب", opt="Test Request"),
				f("service_contract", "Link", "العقد", opt="Service Contract"),
				f("organization", "Link", "المنشأة", opt="Organization"),
				f("file_size", "Data", "الحجم", ro=1),
				f("version", "Int", "الإصدار", default="1"),
				f("content_hash", "Data", "البصمة"),
				f("issued_at", "Datetime", "تاريخ الإصدار"),
				f("retention_until", "Date", "الاحتفاظ حتى"),
			],
			autoname="DOC-.#####",
			title_field="title",
			track_changes=1,
			permissions=admin_full() + [readp(r) for r in (*PARTIES, SUP, SPT)],
		),
		dt(
			"Knowledge Version",
			[
				f("version_code", "Data", "رمز الإصدار", reqd=1, unique=1, in_list=1),
				f("published_on", "Date", "تاريخ النشر"),
				f("status", "Select", "الحالة", opt=KN_STS, default="مسودة", in_list=1, in_std=1),
				f("studies_count", "Int", "عدد الدراسات", ro=1),
				f("changes", "Text", "التغييرات"),
				sec("لقطات"),
				f("table_21", "Table", "Table 2.1", opt="Knowledge Table 21"),
				f("formulas", "Table", "المعادلات", opt="Formula Definition"),
				f("analytical_fields", "Table", "حقول تحليلية", opt="Analytical Field Def"),
				f("recommendation_fields", "Table", "حقول توصيات", opt="Recommendation Field Def"),
				f("manual_fields", "Table", "حقول يدوية", opt="Manual Analysis Field Def"),
				f("engine_triggers", "Table", "المحفّزات", opt="Knowledge Trigger"),
			],
			autoname="field:version_code",
			is_submittable=1,
			title_field="version_code",
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1) + [readp(r) for r in (*PARTIES, SUP, SPT)],
		),
		dt(
			"Report Template",
			[
				f("template_name", "Data", "اسم القالب", reqd=1, in_list=1),
				f("template_key", "Data", "المفتاح", reqd=1, unique=1, in_list=1),
				f("version_code", "Data", "الإصدار"),
				f("standard_ref", "Data", "المرجع المعياري"),
				col("col_rtpl_2"),
				f("status", "Select", "الحالة", opt=TPL_STS, default="مسودة", in_list=1),
				f("print_format", "Link", "تنسيق الطباعة", opt="Print Format"),
				f("usage_count", "Int", "مرات الاستخدام", ro=1),
				sec("أقسام"),
				f("sections", "Table", "الأقسام", opt="Report Template Section"),
				f("history", "Table", "سجل الإصدارات", opt="Template Version History"),
			],
			autoname="field:template_key",
			title_field="template_name",
			track_changes=1,
			permissions=admin_full() + [readp(r) for r in (*PARTIES, SUP, SPT)],
		),
		dt(
			"Policy",
			[
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("version_code", "Data", "الإصدار"),
				f("effective_on", "Date", "يسري من"),
				f("policy_owner", "Data", "المالك"),
				col("col_pol_2"),
				f("status", "Select", "الحالة", opt=POL_STS, default="مسودة", in_list=1),
				f("scope", "Small Text", "النطاق"),
				f("reference_codes", "Small Text", "المراجع"),
				f("body", "Text Editor", "النص"),
			],
			autoname="field:title",
			title_field="title",
			track_changes=1,
			permissions=admin_full() + [readp(r) for r in (*PARTIES, SUP, SPT, VISITOR)],
		),
		dt(
			"Audit Event",
			[
				f("event_time", "Datetime", "الوقت", in_list=1),
				f("actor_user", "Link", "المستخدم", opt="User"),
				f("actor_name", "Data", "اسم الفاعل"),
				f("actor_role", "Data", "الدور"),
				col("col_aud_2"),
				f("organization", "Link", "المنشأة", opt="Organization", in_std=1),
				f("action", "Small Text", "الإجراء", in_list=1),
				f("severity", "Select", "الخطورة", opt="info\nnotice\nwarning\ncritical", in_list=1, in_std=1),
				f("ip", "Data", "IP"),
				sec("الكيان"),
				f("entity_doctype", "Link", "نوع المستند", opt="DocType"),
				f("entity_name", "Dynamic Link", "المستند", opt="entity_doctype"),
				f("detail", "Small Text", "التفصيل"),
			],
			autoname="AUD-.#####",
			track_changes=0,
			hide_toolbar=0,
			permissions=[
				P(SM, read=1, report=1, export=1, print=1),
				P(ADMIN, read=1, report=1, export=1, print=1),
				readp(C_P),
				readp(C_E),
				readp(L_P),
				readp(L_E),
				readp(K_P),
				readp(K_E),
				readp(SUP),
				readp(SPT),
			],
		),
		dt(
			"Support Ticket",
			[
				f("subject", "Data", "الموضوع", reqd=1, in_list=1),
				f("category", "Link", "التصنيف", opt="Ticket Category"),
				f("ticket_status", "Link", "حالة التذكرة", opt="Ticket Status", in_list=1, in_std=1),
				f("status", "Select", "الحالة التشغيلية", opt=TKT_STS, default="مفتوحة", in_list=1),
				col("col_tk_2"),
				f("raised_by", "Link", "مقدم الطلب", opt="User"),
				f("related_request", "Link", "طلب مرتبط", opt="Test Request"),
				f("description", "Text", "الوصف", reqd=1),
			],
			autoname="SUP-.YYYY.-.####",
			title_field="subject",
			track_changes=1,
			permissions=admin_full()
			+ [rwc(r, delete=0) for r in PARTIES]
			+ [rwc(SPT, delete=0), rwc(ADMIN, delete=0)],
		),
		dt(
			"Help Article",
			[
				f("slug", "Data", "المسار", reqd=1, unique=1, in_list=1),
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("audience", "Link", "الجمهور", opt="Organization Type"),
				f("duration_minutes", "Int", "المدة دقائق"),
				f("sort_order", "Int", "الترتيب"),
				f("body", "Text Editor", "المحتوى"),
			],
			autoname="field:slug",
			title_field="title",
			permissions=admin_full()
			+ [readp(r) for r in (*PARTIES, SUP, SPT, VISITOR)]
			+ [rwc(SPT, delete=0)],
		),
		dt(
			"FAQ Entry",
			[
				f("question", "Small Text", "السؤال", reqd=1, in_list=1),
				f("answer", "Text", "الإجابة"),
				f("sort_order", "Int", "الترتيب"),
				f("roles", "Small Text", "الأدوار"),
			],
			autoname="hash",
			title_field="question",
			permissions=admin_full()
			+ [readp(r) for r in (*PARTIES, SUP, SPT, VISITOR)]
			+ [rwc(SPT, delete=0)],
		),
		dt(
			"Useful Link",
			[
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("url", "Data", "الرابط", reqd=1),
				f("sort_order", "Int", "الترتيب"),
			],
			autoname="hash",
			permissions=master_perms(),
		),
		dt(
			"Integration Endpoint",
			[
				f("code", "Data", "الرمز", reqd=1, unique=1, in_list=1),
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("status", "Select", "الحالة", opt=INT_STS, default="يعمل"),
				f("status_note", "Small Text", "ملاحظة"),
				f("last_checked", "Datetime", "آخر فحص"),
			],
			autoname="field:code",
			title_field="title",
			permissions=admin_full() + [readp(r) for r in (*PARTIES, SUP, SPT, VISITOR)],
		),
		dt(
			"Engine Run",
			[
				f("profile", "Link", "الملف", opt="Engine Profile"),
				f("mode", "Select", "الوضع", opt="cloud\nlocal\ncompare", in_list=1),
				f("overall_status", "Select", "الحالة العامة", opt=ENG_STS, in_list=1),
				f("ran_at", "Datetime", "وقت التشغيل", in_list=1),
				col("col_er_2"),
				f("actor", "Link", "المشغّل", opt="User"),
				f("test_request", "Link", "الطلب", opt="Test Request"),
				f("study", "Link", "الدراسة", opt="Geotechnical Study"),
				f("scope_gate_stopped", "Check", "أوقف قبل النموذج"),
				f("effective_for_production", "Check", "فعّال للإنتاج"),
				sec("مسارات"),
				f("cloud_path", "JSON", "المسار السحابي"),
				f("local_path", "JSON", "المسار المحلي"),
				f("comparison", "JSON", "المقارنة"),
				f("result", "JSON", "النتيجة"),
				f("health_snapshot", "JSON", "لقطة الصحة"),
				sec("تكلفة وسياسة"),
				f("cost", "Float", "التكلفة"),
				f("tokens", "Int", "الرموز"),
				f("policy_version", "Data", "إصدار السياسة"),
				f("control_pack_version", "Data", "حزمة الضوابط"),
				f("route_used", "Data", "المسار الفعلي"),
				f("policy_at_run", "Data", "سياسة التوجيه الملتقطة"),
				f("source_file", "Attach", "الملف المصدر"),
			],
			autoname="ER-.#####",
			track_changes=1,
			permissions=admin_full()
			+ [rwc(L_P, delete=0), rwc(L_E, delete=0), rwc(K_P, delete=0), rwc(K_E, delete=0)]
			+ [rwc(SUP, delete=0), readp(SPT)],
		),
		dt(
			"Scheduled Report",
			[
				f("title", "Data", "العنوان", reqd=1, in_list=1),
				f("report_name", "Data", "اسم التقرير", reqd=1),
				f("frequency", "Select", "التكرار", opt="daily\nweekly\nmonthly"),
				f("recipient_user", "Link", "مستلم مستخدم", opt="User"),
				f("recipient_role", "Link", "مستلم دور", opt="Role"),
				f("output_format", "Select", "الصيغة", opt="PDF\nXLSX\nboth"),
				f("last_run", "Datetime", "آخر تشغيل"),
				f("is_active", "Check", "فعّال", default="1"),
			],
			autoname="SR-.#####",
			title_field="title",
			permissions=admin_full() + [rwc(SUP, delete=0), readp(SPT)],
		),
		dt(
			"Principal Transfer",
			[
				f("organization", "Link", "المنشأة", opt="Organization", reqd=1, in_list=1),
				f("from_user", "Link", "المفوّض الحالي", opt="User", reqd=1),
				f("to_user", "Link", "المفوّض الجديد", opt="User", reqd=1),
				f("status", "Select", "الحالة", opt=TR_STS, default="Draft", in_list=1, in_std=1),
				col("col_ptr_2"),
				f("evidence", "Attach", "خطاب التفويض"),
				f("from_otp_ok", "Check", "OTP الطرف الحالي"),
				f("to_otp_ok", "Check", "OTP الطرف الجديد"),
				f("decided_by", "Link", "قرّر", opt="User"),
				f("note", "Small Text", "ملاحظة / طلب توضيح"),
			],
			autoname="PTR-.#####",
			is_submittable=1,
			track_changes=1,
			permissions=admin_full(submit=1, cancel=1)
			+ [rwc(C_P, delete=0, submit=1), rwc(L_P, delete=0, submit=1), rwc(K_P, delete=0, submit=1)]
			+ [readp(SUP), rwc(SPT, delete=0)],
		),
	]


def all_doctypes():
	return children() + masters() + settings_and_party() + catalog_and_commercial() + operations() + rest()


def main():
	docs = all_doctypes()
	names = [d["name"] for d in docs]
	dupes = {n for n in names if names.count(n) > 1}
	if dupes:
		raise SystemExit(f"Duplicate DocTypes: {dupes}")
	for doc in docs:
		write_doctype(APP_ROOT, doc)
	print(f"Wrote {len(docs)} DocTypes ({sum(1 for d in docs if d.get('istable'))} child tables).")


if __name__ == "__main__":
	main()
